[package]
name = "db-client-derive-macro"
version = "0.1.0"
edition = "2021"

[dependencies]
proc-macro2 = "1.0"
proc-macro-error = "1.0"
quote = "1.0.36"
syn = { version = "2.0.58", features = ["visit"] }

[lib]
proc-macro = true